version: "3.4"
x-shared: &common
  ipc: host
  build: .
  volumes:
    - ../:/src/odor_grin_lens
  env_file:
    - .env

services:
  notebook:
    <<: *common
    container_name: ${JUPYTER_NAME}
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: ["tini", "--", "/src/odor_grin_lens/deploy/notebook.sh"]
